version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "🔧 build"
    include: "scope"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: "🔧 build"
    include: "scope"
- package-ecosystem: "npm"
  directory: "/web"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "🔧 build"
    include: "scope"