before:
  hooks:
    - go mod tidy
    - go mod download
    - yarn --cwd web --force install
    - yarn --cwd web run build

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.version=v{{.Version}}"
      - -X "main.gitCommit={{.ShortCommit}}"
      - -X "main.buildDate={{.Now.Format "2006-01-02"}}"
    main: ./cmd/main.go
    binary: gosign

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

brews:
  - repository:
      owner: shurco
      name: homebrew-tap
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    homepage: https://github.com/shurco/gosign
    description: '✍️ Sign documents without stress'
    license: 'MIT'

upx:
  - enabled: false

changelog:
  sort: asc
  filters:
    exclude:
      - init
      - '^.*?ci:'
      - '^.*?test:'
      - '^.*?build(deps):'
      - '^.*?build:'
      - 'README'
      - 'Up'
      - 'merge conflict'
      - Bump
      - Small fix
      - Update
      - Updating
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

dockers:
  - image_templates:
      - 'shurco/gosign:v{{ .Version }}-amd64'
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-amd64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/shurco/gosign/main/README.md'
      - '--label=io.artifacthub.package.maintainers=[{"name":"Dmitry Shurco"}]'
      - '--label=io.artifacthub.package.license=MIT'
      - '--label=org.opencontainers.image.description=✍️ Sign documents without stress'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/amd64'
    goarch: amd64

  - image_templates:
      - 'shurco/gosign:v{{ .Version }}-arm64'
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-arm64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/shurco/gosign/main/README.md'
      - '--label=io.artifacthub.package.maintainers=[{"name":"Dmitry Shurco"}]'
      - '--label=io.artifacthub.package.license=MIT'
      - '--label=org.opencontainers.image.description=✍️ Sign documents without stress'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/arm64'
    goarch: arm64

docker_manifests:
  - name_template: 'shurco/gosign:v{{ .Version }}'
    image_templates:
      - 'shurco/gosign:v{{ .Version }}-amd64'
      - 'shurco/gosign:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/shurco/gosign:v{{ .Version }}'
    image_templates:
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-amd64'
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-arm64'
  - name_template: 'shurco/gosign:latest'
    image_templates:
      - 'shurco/gosign:v{{ .Version }}-amd64'
      - 'shurco/gosign:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/shurco/gosign:latest'
    image_templates:
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-amd64'
      - 'ghcr.io/shurco/gosign:v{{ .Version }}-arm64'

release:
  name_template: "v{{ .Version }}"
  header: |
    > *To update the prebuilt executable you can run `./gosign update`*

  footer: |
    **Full Changelog**: https://github.com/shurco/gosign/compare/{{ .PreviousTag }}...{{ .Tag }}
    
announce:
  mastodon:
    enabled: true
    message_template: "#gosign {{ .Tag }} is out! Check it out: https://github.com/shurco/gosign/releases/tag/{{ .Tag }}"
    server: https://mastodon.social