// Internal server <-> worker contract. The worker exposes this service on a
// private gRPC address (GOSIGN_WORKER_GRPC_ADDR); it must never be published
// on a public network. Every call must carry a bearer token
// (GOSIGN_WORKER_GRPC_TOKEN). Regenerate Go code with: ./scripts/proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/rpc/workerv1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncStatus is the outcome of a mutating maintenance operation.
type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	// The operation completed successfully.
	SyncStatus_SYNC_STATUS_SUCCESS SyncStatus = 1
	// Nothing to do (e.g. database already exists and force=false).
	SyncStatus_SYNC_STATUS_SKIPPED SyncStatus = 2
	// Another worker replica holds the maintenance lock right now.
	SyncStatus_SYNC_STATUS_BUSY SyncStatus = 3
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_SUCCESS",
		2: "SYNC_STATUS_SKIPPED",
		3: "SYNC_STATUS_BUSY",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_SUCCESS":     1,
		"SYNC_STATUS_SKIPPED":     2,
		"SYNC_STATUS_BUSY":        3,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_workerv1_worker_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_internal_rpc_workerv1_worker_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastRunAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	Geolite2Available  bool                   `protobuf:"varint,3,opt,name=geolite2_available,json=geolite2Available,proto3" json:"geolite2_available,omitempty"`
	Geolite2ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=geolite2_modified_at,json=geolite2ModifiedAt,proto3" json:"geolite2_modified_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StatusResponse) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *StatusResponse) GetGeolite2Available() bool {
	if x != nil {
		return x.Geolite2Available
	}
	return false
}

func (x *StatusResponse) GetGeolite2ModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.Geolite2ModifiedAt
	}
	return nil
}

type LookupIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupIPRequest) Reset() {
	*x = LookupIPRequest{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIPRequest) ProtoMessage() {}

func (x *LookupIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIPRequest.ProtoReflect.Descriptor instead.
func (*LookupIPRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *LookupIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LookupIPResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Found   bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	City    string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// Full is the "City, Country" human-readable form.
	Full          string `protobuf:"bytes,4,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupIPResponse) Reset() {
	*x = LookupIPResponse{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIPResponse) ProtoMessage() {}

func (x *LookupIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIPResponse.ProtoReflect.Descriptor instead.
func (*LookupIPResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *LookupIPResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupIPResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LookupIPResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LookupIPResponse) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

type SyncGeoLite2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Download even when the database file already exists.
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Download method: "url" or "maxmind". Empty = use saved settings.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Direct download URL (method "url").
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// MaxMind license key (method "maxmind"). Empty = key from saved settings.
	LicenseKey string `protobuf:"bytes,4,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	// Account to record the last-update timestamp for (optional).
	AccountId     string `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGeoLite2Request) Reset() {
	*x = SyncGeoLite2Request{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGeoLite2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGeoLite2Request) ProtoMessage() {}

func (x *SyncGeoLite2Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGeoLite2Request.ProtoReflect.Descriptor instead.
func (*SyncGeoLite2Request) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGeoLite2Request) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *SyncGeoLite2Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SyncGeoLite2Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SyncGeoLite2Request) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *SyncGeoLite2Request) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type SyncGeoLite2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SyncStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gosign.worker.v1.SyncStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGeoLite2Response) Reset() {
	*x = SyncGeoLite2Response{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGeoLite2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGeoLite2Response) ProtoMessage() {}

func (x *SyncGeoLite2Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGeoLite2Response.ProtoReflect.Descriptor instead.
func (*SyncGeoLite2Response) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *SyncGeoLite2Response) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

type UpdateTrustListsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrustListsRequest) Reset() {
	*x = UpdateTrustListsRequest{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustListsRequest) ProtoMessage() {}

func (x *UpdateTrustListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustListsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrustListsRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{6}
}

type UpdateTrustListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SyncStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gosign.worker.v1.SyncStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrustListsResponse) Reset() {
	*x = UpdateTrustListsResponse{}
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustListsResponse) ProtoMessage() {}

func (x *UpdateTrustListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_workerv1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustListsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrustListsResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_workerv1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTrustListsResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

var File_internal_rpc_workerv1_worker_proto protoreflect.FileDescriptor

const file_internal_rpc_workerv1_worker_proto_rawDesc = "" +
	"\n" +
	"\"internal/rpc/workerv1/worker.proto\x12\x10gosign.worker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStatusRequest\"\x84\x02\n" +
	"\x0eStatusResponse\x129\n" +
	"\n" +
	"started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\vlast_run_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12-\n" +
	"\x12geolite2_available\x18\x03 \x01(\bR\x11geolite2Available\x12L\n" +
	"\x14geolite2_modified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x12geolite2ModifiedAt\"!\n" +
	"\x0fLookupIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"j\n" +
	"\x10LookupIPResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x12\n" +
	"\x04full\x18\x04 \x01(\tR\x04full\"\x95\x01\n" +
	"\x13SyncGeoLite2Request\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\vlicense_key\x18\x04 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\"L\n" +
	"\x14SyncGeoLite2Response\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.gosign.worker.v1.SyncStatusR\x06status\"\x19\n" +
	"\x17UpdateTrustListsRequest\"P\n" +
	"\x18UpdateTrustListsResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.gosign.worker.v1.SyncStatusR\x06status*q\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SYNC_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13SYNC_STATUS_SKIPPED\x10\x02\x12\x14\n" +
	"\x10SYNC_STATUS_BUSY\x10\x032\xf9\x02\n" +
	"\rWorkerService\x12K\n" +
	"\x06Status\x12\x1f.gosign.worker.v1.StatusRequest\x1a .gosign.worker.v1.StatusResponse\x12Q\n" +
	"\bLookupIP\x12!.gosign.worker.v1.LookupIPRequest\x1a\".gosign.worker.v1.LookupIPResponse\x12]\n" +
	"\fSyncGeoLite2\x12%.gosign.worker.v1.SyncGeoLite2Request\x1a&.gosign.worker.v1.SyncGeoLite2Response\x12i\n" +
	"\x10UpdateTrustLists\x12).gosign.worker.v1.UpdateTrustListsRequest\x1a*.gosign.worker.v1.UpdateTrustListsResponseB9Z7github.com/shurco/gosign/internal/rpc/workerv1;workerv1b\x06proto3"

var (
	file_internal_rpc_workerv1_worker_proto_rawDescOnce sync.Once
	file_internal_rpc_workerv1_worker_proto_rawDescData []byte
)

func file_internal_rpc_workerv1_worker_proto_rawDescGZIP() []byte {
	file_internal_rpc_workerv1_worker_proto_rawDescOnce.Do(func() {
		file_internal_rpc_workerv1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_workerv1_worker_proto_rawDesc), len(file_internal_rpc_workerv1_worker_proto_rawDesc)))
	})
	return file_internal_rpc_workerv1_worker_proto_rawDescData
}

var file_internal_rpc_workerv1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_rpc_workerv1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_rpc_workerv1_worker_proto_goTypes = []any{
	(SyncStatus)(0),                  // 0: gosign.worker.v1.SyncStatus
	(*StatusRequest)(nil),            // 1: gosign.worker.v1.StatusRequest
	(*StatusResponse)(nil),           // 2: gosign.worker.v1.StatusResponse
	(*LookupIPRequest)(nil),          // 3: gosign.worker.v1.LookupIPRequest
	(*LookupIPResponse)(nil),         // 4: gosign.worker.v1.LookupIPResponse
	(*SyncGeoLite2Request)(nil),      // 5: gosign.worker.v1.SyncGeoLite2Request
	(*SyncGeoLite2Response)(nil),     // 6: gosign.worker.v1.SyncGeoLite2Response
	(*UpdateTrustListsRequest)(nil),  // 7: gosign.worker.v1.UpdateTrustListsRequest
	(*UpdateTrustListsResponse)(nil), // 8: gosign.worker.v1.UpdateTrustListsResponse
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_internal_rpc_workerv1_worker_proto_depIdxs = []int32{
	9, // 0: gosign.worker.v1.StatusResponse.started_at:type_name -> google.protobuf.Timestamp
	9, // 1: gosign.worker.v1.StatusResponse.last_run_at:type_name -> google.protobuf.Timestamp
	9, // 2: gosign.worker.v1.StatusResponse.geolite2_modified_at:type_name -> google.protobuf.Timestamp
	0, // 3: gosign.worker.v1.SyncGeoLite2Response.status:type_name -> gosign.worker.v1.SyncStatus
	0, // 4: gosign.worker.v1.UpdateTrustListsResponse.status:type_name -> gosign.worker.v1.SyncStatus
	1, // 5: gosign.worker.v1.WorkerService.Status:input_type -> gosign.worker.v1.StatusRequest
	3, // 6: gosign.worker.v1.WorkerService.LookupIP:input_type -> gosign.worker.v1.LookupIPRequest
	5, // 7: gosign.worker.v1.WorkerService.SyncGeoLite2:input_type -> gosign.worker.v1.SyncGeoLite2Request
	7, // 8: gosign.worker.v1.WorkerService.UpdateTrustLists:input_type -> gosign.worker.v1.UpdateTrustListsRequest
	2, // 9: gosign.worker.v1.WorkerService.Status:output_type -> gosign.worker.v1.StatusResponse
	4, // 10: gosign.worker.v1.WorkerService.LookupIP:output_type -> gosign.worker.v1.LookupIPResponse
	6, // 11: gosign.worker.v1.WorkerService.SyncGeoLite2:output_type -> gosign.worker.v1.SyncGeoLite2Response
	8, // 12: gosign.worker.v1.WorkerService.UpdateTrustLists:output_type -> gosign.worker.v1.UpdateTrustListsResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_rpc_workerv1_worker_proto_init() }
func file_internal_rpc_workerv1_worker_proto_init() {
	if File_internal_rpc_workerv1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_workerv1_worker_proto_rawDesc), len(file_internal_rpc_workerv1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_workerv1_worker_proto_goTypes,
		DependencyIndexes: file_internal_rpc_workerv1_worker_proto_depIdxs,
		EnumInfos:         file_internal_rpc_workerv1_worker_proto_enumTypes,
		MessageInfos:      file_internal_rpc_workerv1_worker_proto_msgTypes,
	}.Build()
	File_internal_rpc_workerv1_worker_proto = out.File
	file_internal_rpc_workerv1_worker_proto_goTypes = nil
	file_internal_rpc_workerv1_worker_proto_depIdxs = nil
}
