// Internal server <-> worker contract. The worker exposes this service on a
// private gRPC address (GOSIGN_WORKER_GRPC_ADDR); it must never be published
// on a public network. Every call must carry a bearer token
// (GOSIGN_WORKER_GRPC_TOKEN). Regenerate Go code with: ./scripts/proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/rpc/workerv1/worker.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Status_FullMethodName           = "/gosign.worker.v1.WorkerService/Status"
	WorkerService_LookupIP_FullMethodName         = "/gosign.worker.v1.WorkerService/LookupIP"
	WorkerService_SyncGeoLite2_FullMethodName     = "/gosign.worker.v1.WorkerService/SyncGeoLite2"
	WorkerService_UpdateTrustLists_FullMethodName = "/gosign.worker.v1.WorkerService/UpdateTrustLists"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService serves requests coming from the API server. Workers may run
// as multiple replicas: mutating operations are serialized with a Postgres
// advisory lock, so exactly one replica performs the update at a time.
type WorkerServiceClient interface {
	// Status reports worker health and the state of maintenance tasks.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// LookupIP resolves an IP address to a location using the GeoLite2
	// database owned by the worker.
	LookupIP(ctx context.Context, in *LookupIPRequest, opts ...grpc.CallOption) (*LookupIPResponse, error)
	// SyncGeoLite2 triggers an on-demand GeoLite2 database refresh.
	SyncGeoLite2(ctx context.Context, in *SyncGeoLite2Request, opts ...grpc.CallOption) (*SyncGeoLite2Response, error)
	// UpdateTrustLists triggers an on-demand Adobe trust list refresh.
	UpdateTrustLists(ctx context.Context, in *UpdateTrustListsRequest, opts ...grpc.CallOption) (*UpdateTrustListsResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, WorkerService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) LookupIP(ctx context.Context, in *LookupIPRequest, opts ...grpc.CallOption) (*LookupIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupIPResponse)
	err := c.cc.Invoke(ctx, WorkerService_LookupIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SyncGeoLite2(ctx context.Context, in *SyncGeoLite2Request, opts ...grpc.CallOption) (*SyncGeoLite2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncGeoLite2Response)
	err := c.cc.Invoke(ctx, WorkerService_SyncGeoLite2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UpdateTrustLists(ctx context.Context, in *UpdateTrustListsRequest, opts ...grpc.CallOption) (*UpdateTrustListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTrustListsResponse)
	err := c.cc.Invoke(ctx, WorkerService_UpdateTrustLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService serves requests coming from the API server. Workers may run
// as multiple replicas: mutating operations are serialized with a Postgres
// advisory lock, so exactly one replica performs the update at a time.
type WorkerServiceServer interface {
	// Status reports worker health and the state of maintenance tasks.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// LookupIP resolves an IP address to a location using the GeoLite2
	// database owned by the worker.
	LookupIP(context.Context, *LookupIPRequest) (*LookupIPResponse, error)
	// SyncGeoLite2 triggers an on-demand GeoLite2 database refresh.
	SyncGeoLite2(context.Context, *SyncGeoLite2Request) (*SyncGeoLite2Response, error)
	// UpdateTrustLists triggers an on-demand Adobe trust list refresh.
	UpdateTrustLists(context.Context, *UpdateTrustListsRequest) (*UpdateTrustListsResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedWorkerServiceServer) LookupIP(context.Context, *LookupIPRequest) (*LookupIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupIP not implemented")
}
func (UnimplementedWorkerServiceServer) SyncGeoLite2(context.Context, *SyncGeoLite2Request) (*SyncGeoLite2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGeoLite2 not implemented")
}
func (UnimplementedWorkerServiceServer) UpdateTrustLists(context.Context, *UpdateTrustListsRequest) (*UpdateTrustListsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrustLists not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_LookupIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).LookupIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_LookupIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).LookupIP(ctx, req.(*LookupIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SyncGeoLite2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGeoLite2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SyncGeoLite2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SyncGeoLite2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SyncGeoLite2(ctx, req.(*SyncGeoLite2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UpdateTrustLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrustListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UpdateTrustLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UpdateTrustLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UpdateTrustLists(ctx, req.(*UpdateTrustListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gosign.worker.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _WorkerService_Status_Handler,
		},
		{
			MethodName: "LookupIP",
			Handler:    _WorkerService_LookupIP_Handler,
		},
		{
			MethodName: "SyncGeoLite2",
			Handler:    _WorkerService_SyncGeoLite2_Handler,
		},
		{
			MethodName: "UpdateTrustLists",
			Handler:    _WorkerService_UpdateTrustLists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/workerv1/worker.proto",
}
