#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

ARCH="$(uname -m)"
case "$ARCH" in
i386|i686) ARCH="386" ;;
x86_64|amd64) ARCH="amd64" ;;
arm64|aarch64) ARCH="arm64" ;;
esac

OS="$(uname -s)"

if command -v tput >/dev/null 2>&1 && [ -n "${TERM:-}" ] && tput colors >/dev/null 2>&1; then
  COLOR_GREY="$(tput setaf 0 2>/dev/null || true)"
  COLOR_RED="$(tput setaf 1 2>/dev/null || true)"
  COLOR_GREEN="$(tput setaf 2 2>/dev/null || true)"
  COLOR_YELLOW="$(tput setaf 3 2>/dev/null || true)"
  COLOR_RESET="$(tput sgr0 2>/dev/null || true)"
else
  COLOR_GREY=""
  COLOR_RED=""
  COLOR_GREEN=""
  COLOR_YELLOW=""
  COLOR_RESET=""
fi

maybe_sudo() {
  if [ "$(id -u)" -ne 0 ]; then
    sudo "$@"
  else
    "$@"
  fi
}

support_arch() {
  if [ "$ARCH" != "amd64" ] && [ "$ARCH" != "arm64" ]; then
    print_answer "ERROR" red
    echo "unsupported architecture: $ARCH"
    exit 1
  fi
}

command_exists() {
  command -v "$@" >/dev/null 2>&1
}

print_answer() {
  local COLOR="$COLOR_RESET"
  for flag in "$@"; do
    case $flag in
    grey) COLOR=$COLOR_GREY ;;
    green) COLOR=$COLOR_GREEN ;;
    yellow) COLOR=$COLOR_YELLOW ;;
    red) COLOR=$COLOR_RED ;;
    esac
  done
  echo "${COLOR}$1${COLOR_RESET}" >&2
}

print_header() {
  printf "%.45s " "$* ........................................"
}

print_help() {
  printf "%.20s " "${COLOR_GREEN}$1${COLOR_RESET}                       "
  echo "$2" >&2
}
