#!/usr/bin/env bash

#set -e

ROOT_PATH="$(git rev-parse --show-toplevel)"
source ${ROOT_PATH}/scripts/_helper

arr_process=(__debug_bin vite)
for process in "${arr_process[@]}"; do
  if pkill -f "$process" >/dev/null; then
    print_header "Killing $process process"
    print_answer "SUCCESS" green
  fi
done

print_header "Remove old bin and dist files"
for entry in ${ROOT_PATH}/cmd/*/; do
  name=$(basename "${entry}")
  rm -rf ${ROOT_PATH}/cmd/${name}/__debug_bin*
done
rm -rf ${ROOT_PATH}/web/dist
print_answer "SUCCESS" green


print_header "Remove uploaded files"
arr_folders=(lc_signed lc_tmp lc_uploads)
for folder in "${arr_folders[@]}"; do
  rm -rf ${ROOT_PATH}/cmd/goSign/${folder}/*
done
print_answer "SUCCESS" green
